---
title: "p8105_hw2_hh3043"
author: "Haitian Huang"
date: "2023-10-02"
output: html_document
---
```{r}
library(tidyverse)
library(read_excel)
```

problem 1

First,clean the pols_month dataset.
```{r}

pols_month = 
  read_csv('.\\fivethirtyeight_datasets\\pols-month.csv')|>
  separate(mon,into = c('year','month','day'),convert=TRUE) |>
  mutate(month=month.name[month])|>
  mutate(
    president = case_match(prez_gop, 0 ~ "dem",
                         1 ~ "gop", 
                         2 ~ "gop"))|>
  select(year,month,everything(),-day,-starts_with('prez_'))





```
Then, clean the snp dataset.

```{r}
snp = read_csv('.\\fivethirtyeight_datasets\\snp.csv')|>
  separate(date,into = c('day','month','year'),convert = TRUE) |>
  mutate(
    year = if_else(year>23,year+1900,year+2000),
    month = month.name[month]
  )
```
Third,clean the unemployment data.
```{r}
unemployment = read_csv('.\\fivethirtyeight_datasets\\unemployment.csv')|> 
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(
    month = month.name[match(month,month.abb)]
  )
```
Finally,join all three data sets.

```{r}
data_538 = left_join(pols_month,snp)|>
  left_join(x=_,unemployment)
```

problem 2

Clean the Mr.Trash data set and dcalculate the homes powered.
```{r}



Mr_Trash = read_excel('202207 Trash Wheel Collection Data.xlsx',range = cell_cols('A:N'))|>
  janitor::clean_names() |>
  rename(homes_powered_approximate = homes_powered)|>
  drop_na('dumpster')|>
  mutate(
    homes_powered = weight_tons*500/30)
```













